defaults: &defaults
  machine:
    php:
      version: 7.2

phpunit: &phpunit
  steps:
    - checkout
    - run: sudo add-apt-repository ppa:ondrej/php -y
    - run: sudo apt-get update
    - run: sudo apt-get install php7.2-dev
    - run: sudo apt-get install php7.2-mbstring
    - run: mkdir -p library
    - run: cd library && git clone https://github.com/runkit7/runkit7.git && cd runkit7 && phpize && ./configure && make && sudo make install && echo -e "extension=runkit\nrunkit.internal_override=1" | sudo tee -a /etc/php/7.2/cli/php.ini
    - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - run: php -r "if (hash_file('sha384', 'composer-setup.php') ===  '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - run: php composer-setup.php
    - run: php -r "unlink('composer-setup.php');"
    - run: php composer.phar self-update
    - run: sudo mv composer.phar /usr/local/bin/composer
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
    - run: composer install -n --prefer-dist
    - save_cache:
        paths:
          - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}
    - run: composer code-style
    - run: composer test

version: 2
jobs:
  build:
    <<: *defaults
    <<: *phpunit
